services:
  webhook:
    container_name: webhook
    image: webhook
    build:
      context: .
    restart: always
    environment:
      - RUST_LOG=info
      - SECRET=${SECRET}
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.webhook.rule: Host(`webhook.foxochat.app`)
      traefik.http.services.webhook.loadbalancer.server.port: 8080
      traefik.http.routers.webhook.middlewares: ratelimit@file

networks:
  traefik:
    external: true
