name: Deploy Webhook

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: cloud
    steps:
      - uses: actions/checkout@v4

      - name: Run Webhook
        run: docker compose up -e DISCORD_WEBHOOK ${{ secrets.DISCORD_WEBHOOK }} -d --build
