name: Deploy Webhook

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: cloud
    steps:
      - uses: actions/checkout@v4

      - name: Run Webhook
        env:
          SECRET: ${{ secrets.SECRET }}
        run: docker compose up -d --build
