name: Deploy Webhook

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: cloud
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker build -t foxogram/webhook:local .

      - name: Run
        env:
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
          NOMAD_VAR_secret: ${{ secrets.SECRET }}
        run: nomad job run nomad.hcl
